#!/bin/sh

cd "`dirname $0`"
script=`basename $0`
if test -L "$script"; then
  INCDIR=`dirname $(readlink "$script")`
  cd "$INCDIR"
fi
INCDIR=`pwd`

exec php -C -q -d include_path="$INCDIR" -d open_basedir="" -d safe_mode=0 -d register_argc_argv="On" -d auto_prepend_file="" -d auto_append_file="" "$INCDIR/PHP/ParserGenerator/cli.php" "$@"
