#!/usr/bin/env php
<?php

include dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . "autoload.php";

require __DIR__ .
    DIRECTORY_SEPARATOR . "PHP" .
    DIRECTORY_SEPARATOR . "ParserGenerator" .
    DIRECTORY_SEPARATOR . "cli.php";
