#!/usr/bin/env php
<?php

function php_parsergenerator_autoload($cls)
{
    $cls = ltrim($cls, '\\');
    if (!strncmp($cls, "PHP_ParserGenerator", 19)) {
        require __DIR__ . DIRECTORY_SEPARATOR .
                str_replace('_', DIRECTORY_SEPARATOR, $cls) . '.php';
    }
    return false;
}
spl_autoload_register('php_parsergenerator_autoload', true, true);

$pg = new PHP_ParserGenerator;
$pg->main();
